### ISSUE TITLE
Issue on importing

### ISSUE THREAD

**Issue by wgottschalk-RMS** [mdgriffith/elm-style-animation#12]
When I do imports, I like to be explicit about exposing types and functions. When I try and import specific types into my module I get the following error:
```
-- NAMING ERROR --------------------------------------- ././Components/Movie.elm

Module `Style.Properties` does not expose `Width`

8| import Style.Properties exposing (Width)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
But when I type `Import Style.Properties exposing(..)` it works just fine. This is confusing because 
I can also use `Style.Properties.Width` and that compiles. There is no documentation on this nor are the specific imports in any of the examples

**Comment by mdgriffith** [comment]
So, the issue is that in Elm you can't import a specific constructor of a type, only an entire type.  In this case you have to import `Style.Properties.Property (..)` (which is all properties).  I know, I know, not the best.

BUT, the new major version I'm working on will be able to do what you're talking about.

I'm hoping to have it finalized by early next week. Sooo, there's that.

 Thanks for the issue!
