### ISSUE TITLE
SVG height and width attributes

### ISSUE THREAD

**Issue by marick** [mdgriffith/elm-style-animation#27]
I'm animating SVG `rect` elements to show [fluid levels decreasing](https://new.critter4us.com/iv). `rect` uses `height` and `width` attributes. Those aren't animatable via the API. I realize I could use `points` instead of `rect`, but these attributes might be broadly useful. (Alternately, perhaps a way to set custom SVG attributes, though the case statement in [the code](https://github.com/mdgriffith/elm-style-animation/blob/master/src/Animation.elm#L1859) suggests that isn't straightforward.)

Interestingly, you *can* use the HTML height attribute, which results in an element like this:

```html
<rect style="height: 0px;" y="90" fill="#d3d7cf" x="0" width="30"></rect>
```

That actually works in both Chrome and Safari, but not in Firefox.

**Comment by mdgriffith** [comment]
Hey!  Sorry, long time in responding :/  

You can do this if you use `Animation.attr "height" 0 "px"`, which manually specifies something that should render as an attribute instead of a style property.

I've put this on the list of things I'm looking at (rendering `Animation.height` as both a property and a style attribute) when I work on the next major revision.

Thanks!
