### ISSUE TITLE
Add type to the docs

### ISSUE THREAD

**Issue by Birowsky** [mdgriffith/elm-style-animation#30]
It should be a good idea to add the `Animation.State` to the docs because the compiler is suggesting something totally different: `Animation.Model.Animation msg`. I had to look in one of your repos to figure out the type.

**Comment by mdgriffith** [comment]
I'm a little unclear as to what you mean.  `Animation.State` is in the docs as a synonym for `Animation Never`.   Do you want me to add a note that `Animation Never` is shorthand for `Animation.Model.Animation Never`?

**Comment by Birowsky** [comment]
Oh, you decide what to do. This was my experience:

- whoa, nice anim lib. And it uses springs? FTW!
- let's go through the basic, add `style` to `init`
- let's update the Model with what the compiler suggests `Animation.Model.Animation msg`
- get a compiler error: no such module `Animation.Model`
- get frustrated
- look through author repos to see how he uses it
- finally locate an example (it's different than what the compiler suggests)
- but it works!
- notify the author :}

so yeah, you decide. I'm off to step two :}

you should kinda figure that i'm a beginner

**Comment by ento** [comment]
I have another usecase for exposing types used in the type annotations of already exposed functions:

- wanted to add a type annotation to an internal helper function that is a shorthand for `Animation.interrupt` combined with `Animation.translateX`
- got to a point where I can't move forward without having `Animation.Length` exposed

the function in question

```elm
translateX : x -> (Animation.State -> Animation.State)
translateX length =
    Animation.interrupt
        [ Animation.to
            [ Animation.translate length (Animation.px 0) ]
        ]
```

error from the compiler:

```sh
The 1st argument to function `translate` is causing a mismatch.

250|               Animation.translate length (Animation.px 0)
                                       ^^^^^^
Function `translate` is expecting the 1st argument to be:

    Animation.Length

But it is:

    x
```

It'd be great if at least `Animation.Length` without its members is exposed: `module Animation exposing (..., Length, ...)`.

As a broader, catch-all request, it'd be even greater if all types used in the type annotations of exposed functions are also exposed so that people can annotate functions that pass their argument(s) to one of the `Animation` functions.

**Comment by mdgriffith** [comment]
A few comments have been added and `Animation.Length` and `Animation.Angle` opaque types are now exposed :).

**Comment by ento** [comment]
Yay, thanks for taking the time!

One more thing: I noticed that the version field in `elm-package.json` is still 3.5.0 when I go to browse the source of 3.5.1: https://github.com/mdgriffith/elm-style-animation/blob/3.5.1/elm-package.json#L2

**Comment by mdgriffith** [comment]
Thanks for the heads up!  That should be fixed now
