### ISSUE TITLE
source code learning, some question

### ISSUE THREAD

**Issue by raiscui** [mdgriffith/elm-style-animation#46]
Hi,  i'm wirting a framework for elm, want Integrate **elm-style-animation** 
i read code ,and have some question:

- in the `resolveSteps`  

the `Step ->`  already did `List.all isDone stepped` ,  
why `To target -> `  do same by `alreadyThere`?  both run `function: step dt props` , i think it's unnecessary ,can you explain this?

- in `alreadyThere` ,

 why use `step 0` ,is that `step 16.666` do same thing?

**Comment by raiscui** [comment]
in `resolveSteps` `Step ->` 

when stepped done, why need reset `interpolationOverride = Nothing` for them?  for now, the `resolveSteps` return things `revisedStyle` is just use for set current model.style , why necessary do this?

**Comment by mdgriffith** [comment]
I'm going to close this because this isn't a bug, but I'm happy to answer a question or two :)

`step 0` is how an animation is initialized without going anywhere, which is necessary to check for the case of `eased.progress == 0 && motion.position == motion.target` in `isDone`.

So this is what needs to happen:

- `step 0` -> Initializes animation so that eased.progress is 0 and position doesn't change
- `List.all isDone` -> Check to see if it's "already finished"
- `step 16.66` -> Step Normally
- `List.all isDone` -> Check to see if it's finished after one step
